### ISSUE TITLE
Potentially different behaviour

### ISSUE THREAD

**Issue by zoffixznet** [lizmat/P5quotemeta#1]
I was going through [the list of Perl 5 changes](https://tech.binary.com/perl-5-24-changes/) and I see this item:

> Characters quoted by quotemeta() have changed (specifically, a few extra Unicode codepoints are quoted - the ASCII range is unaffected).

When I first made the module, I generated the list to escape by seeing what Perl 5 escaped.

I think the [char-finder.pl script](https://github.com/lizmat/P5quotemeta/blob/master/char-finder.pl) is what was used, but I've no idea if the 5.20 it lists is what I was using at the time and whether the changes to quotemeta that were made are included in the original list that was generated.

**Comment by lizmat** [comment]
The lists appear the same, at least for 5.28 I just tried.  It does seem to point to some weird interactions in the way char classes are compiled, which could point to an nqp issue.  But leaving that for now.  So closing this now (finally).
